In [1]:
import pandas as pd

## loc
- single label
    เรียก "datsun 710 " มาดูข้อมูล

- list of label
- slice object
- boolean array

In [2]:
pd.__version__

'2.2.0'

In [5]:
df = pd.read_csv('mtcars.csv',
                nrows=10,
                index_col='model')
df

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
model                                                                        
Mazda RX4          21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
Mazda RX4 Wag      21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
Datsun 710         22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
Hornet 4 Drive     21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   
Valiant            18.1    6  225.0  105  2.76  3.460  20.22   1   0     3   
Duster 360         14.3    8  360.0  245  3.21  3.570  15.84   0   0     3   
Merc 240D          24.4    4  146.7   62  3.69  3.190  20.00   1   0     4   
Merc 230           22.8    4  140.8   95  3.92  3.150  22.90   1   0     4   
Merc 280           19.2    6  167.6  123  3.92  3.440  18.30   1   0     4   

                   carb  
model                    
Mazda RX4             4  
Mazda RX4 Wag         4  
Datsun 710            1  
Hornet 4 Drive        1  
Hornet Sportabout     2  
Valiant               1  
Duster 360            4  
Merc 240D             2  
Merc 230              2  
Merc 280              4

In [7]:
df.loc['Datsun 710']

mpg      22.80
cyl       4.00
disp    108.00
hp       93.00
drat      3.85
wt        2.32
qsec     18.61
vs        1.00
am        1.00
gear      4.00
carb      1.00
Name: Datsun 710, dtype: float64

In [8]:
df.loc[['Datsun 710']]

mpg  cyl   disp  hp  drat    wt   qsec  vs  am  gear  carb
model                                                                  
Datsun 710  22.8    4  108.0  93  3.85  2.32  18.61   1   1     4     1

In [9]:
df.loc[['Datsun 710'], :]

mpg  cyl   disp  hp  drat    wt   qsec  vs  am  gear  carb
model                                                                  
Datsun 710  22.8    4  108.0  93  3.85  2.32  18.61   1   1     4     1

In [10]:
df.loc[['Datsun 710'], 'mpg']

model
Datsun 710    22.8
Name: mpg, dtype: float64

# list of label

In [11]:
df.loc[['Datsun 710','Merc 230']]

mpg  cyl   disp  hp  drat    wt   qsec  vs  am  gear  carb
model                                                                  
Datsun 710  22.8    4  108.0  93  3.85  2.32  18.61   1   1     4     1
Merc 230    22.8    4  140.8  95  3.92  3.15  22.90   1   0     4     2

df.loc[['Datsun 710','Merc 230'],'mpg':'hp']

In [13]:
df.loc[['Datsun 710','Merc 230'],['mpg','hp']]

mpg  hp
model               
Datsun 710  22.8  93
Merc 230    22.8  95

In [14]:
# slice object

In [15]:
df.loc['Datsun 710':'Merc 230']

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
model                                                                        
Datsun 710         22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
Hornet 4 Drive     21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   
Valiant            18.1    6  225.0  105  2.76  3.460  20.22   1   0     3   
Duster 360         14.3    8  360.0  245  3.21  3.570  15.84   0   0     3   
Merc 240D          24.4    4  146.7   62  3.69  3.190  20.00   1   0     4   
Merc 230           22.8    4  140.8   95  3.92  3.150  22.90   1   0     4   

                   carb  
model                    
Datsun 710            1  
Hornet 4 Drive        1  
Hornet Sportabout     2  
Valiant               1  
Duster 360            4  
Merc 240D             2  
Merc 230              2

In [16]:
df.loc['Datsun 710':'Merc 230','hp':'gear']

hp  drat     wt   qsec  vs  am  gear
model                                                   
Datsun 710          93  3.85  2.320  18.61   1   1     4
Hornet 4 Drive     110  3.08  3.215  19.44   1   0     3
Hornet Sportabout  175  3.15  3.440  17.02   0   0     3
Valiant            105  2.76  3.460  20.22   1   0     3
Duster 360         245  3.21  3.570  15.84   0   0     3
Merc 240D           62  3.69  3.190  20.00   1   0     4
Merc 230            95  3.92  3.150  22.90   1   0     4

# boolean array

In [18]:
df.index.str.contains('Merc')

array([False, False, False, False, False, False, False,  True,  True,
        True])

In [19]:
df.loc[df.index.str.contains('Merc')]

mpg  cyl   disp   hp  drat    wt  qsec  vs  am  gear  carb
model                                                                 
Merc 240D  24.4    4  146.7   62  3.69  3.19  20.0   1   0     4     2
Merc 230   22.8    4  140.8   95  3.92  3.15  22.9   1   0     4     2
Merc 280   19.2    6  167.6  123  3.92  3.44  18.3   1   0     4     4

In [20]:
df.loc[df.index.str.contains('Merc'), 'mpg']

model
Merc 240D    24.4
Merc 230     22.8
Merc 280     19.2
Name: mpg, dtype: float64

In [21]:
df.loc[df.index.str.contains('Merc'), 'mpg':'hp']

mpg  cyl   disp   hp
model                           
Merc 240D  24.4    4  146.7   62
Merc 230   22.8    4  140.8   95
Merc 280   19.2    6  167.6  123